<?php

namespace Database\Factories;

use App\Models\Category;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Task>
 */

/**
 * Factory for creating Task model instances.
 *
 * Fields:
 * - title: A sentence generated by Faker.
 * - description: A paragraph generated by Faker.
 * - category_id: Associated category created by CategoryFactory.
 * - is_completed: Defaulted to false.
 */
class TaskFactory extends Factory
{
    public function definition(): array
    {
        return [
            'title' => $this->faker->sentence,
            'description' => $this->faker->paragraph,
            'category_id' => Category::factory(),
            'is_completed' => false,
        ];
    }
}
